import { initializeApp } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-app.js";
import { getAuth, GoogleAuthProvider, signInWithPopup, signOut, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js";
import { getFirestore, collection, doc, addDoc, updateDoc, deleteDoc, getDocs, writeBatch, onSnapshot, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js";

const firebaseConfig={apiKey:"AIzaSyDXua-vkZB-KzPZaZVvSJXvO6CrJYhCl3Q",authDomain:"xuedasecondary-game-hub.firebaseapp.com",projectId:"xuedasecondary-game-hub",storageBucket:"xuedasecondary-game-hub.firebasestorage.app",messagingSenderId:"210198650990",appId:"1:210198650990:web:905cb1ff8a44c80f1ac67f",measurementId:"G-2ZVM89DMCG"};
const ADMIN_EMAIL="teechaisoon@xuedaeducationgroup.edu.my";
const SUBJECTS=[{id:"BMP",name:"BMP",full:"Bahasa Melayu Pemahaman"},{id:"BMK",name:"BMK",full:"Bahasa Melayu Karangan"},{id:"BI",name:"BI",full:"Bahasa Inggeris"},{id:"SEJ",name:"SEJ",full:"Sejarah"},{id:"MM",name:"MM",full:"Matematik"},{id:"SC",name:"SC",full:"Sains"}];
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),provider=new GoogleAuthProvider();
let data={folders:[],items:[]},currentSubject=null,currentFolder=null,searchTerm="",user=null,isAdmin=false;
const $=id=>document.getElementById(id);
const esc=(v="")=>String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const uid=()=>`${Date.now()}-${Math.random().toString(36).slice(2,8)}`;
function toast(message){$("toast").textContent=message;$("toast").classList.add("show");setTimeout(()=>$("toast").classList.remove("show"),2000)}
function addAuthButton(){const actions=document.querySelector(".header-actions"),button=document.createElement("button");button.id="authButton";button.className="secondary-button";actions.appendChild(button);button.onclick=async()=>{try{user?await signOut(auth):await signInWithPopup(auth,provider)}catch(error){console.error(error);toast("登录失败，请检查弹出窗口或授权域名")}}}
function renderAuth(){const button=$("authButton");if(!button)return;button.textContent=user?(isAdmin?"管理员 · 登出":"访客 · 登出"):"Google 登录";$("newFolderButton").hidden=!isAdmin;$("newHtmlButton").hidden=!isAdmin}
function renderNav(){$("subjectNav").innerHTML=`<button class="subject-link ${!currentSubject?"active":""}" data-subject=""><span class="dot"></span>资源总览</button>`+SUBJECTS.map(s=>`<button class="subject-link ${currentSubject===s.id?"active":""}" data-subject="${s.id}"><span class="dot"></span>${s.name}<small>${s.full}</small></button>`).join("")}
function renderDashboard(){const cards=SUBJECTS.map(s=>{const folders=data.folders.filter(f=>f.subject===s.id).length,items=data.items.filter(i=>i.subject===s.id).length;return `<article class="resource-card"><div class="card-icon">${s.name}</div><h3 class="card-title">${s.name}</h3><p class="card-description">${s.full}</p><p class="card-meta">${folders} 个文件夹 · ${items} 个网页</p><div class="card-actions"><button class="mini-button" data-open-subject="${s.id}">进入科目 →</button></div></article>`}).join("");$("dashboardView").innerHTML=`<section class="welcome"><p class="eyebrow">XUEDA EDUCATION</p><h2>一站式管理你的 HTML 教学工具</h2><p>资源现已储存在云端。管理员可以编辑，其他使用者可以查看及开启教学网页。</p></section><section class="section-block"><div class="section-heading"><div><p>SUBJECTS</p><h2>全部科目</h2></div></div><div class="card-grid">${cards}</div></section>`}
const matches=text=>!searchTerm||String(text).toLowerCase().includes(searchTerm);
function actions(type,id){if(!isAdmin)return "";return type==="folder"?`<button class="mini-button" data-edit-folder="${id}">改名</button><button class="mini-button danger" data-delete-folder="${id}">删除</button>`:`<button class="mini-button" data-edit-html="${id}">编辑</button><button class="mini-button danger" data-delete-html="${id}">删除</button>`}
function renderSubject(){const subject=SUBJECTS.find(s=>s.id===currentSubject),folders=data.folders.filter(f=>f.subject===currentSubject&&matches(f.name));let items=data.items.filter(i=>i.subject===currentSubject);if(currentFolder)items=items.filter(i=>i.folderId===currentFolder);items=items.filter(i=>matches(`${i.title} ${i.description||""}`));$("currentSubjectName").textContent=`${subject.name} · ${subject.full}`;$("folderCount").textContent=data.folders.filter(f=>f.subject===currentSubject).length;$("htmlCount").textContent=data.items.filter(i=>i.subject===currentSubject).length;$("folderGrid").innerHTML=folders.length?folders.map(f=>`<article class="resource-card"><div class="card-icon">▰</div><h3 class="card-title">${esc(f.name)}</h3><p class="card-meta">${data.items.filter(i=>i.folderId===f.id).length} 个 HTML 网页</p><div class="card-actions"><button class="mini-button" data-open-folder="${f.id}">打开</button>${actions("folder",f.id)}</div></article>`).join(""):`<div class="empty-state">${isAdmin?'还没有文件夹。点击右上角“新建文件夹”。':'这里还没有文件夹。'}</div>`;$("htmlSectionTitle").textContent=currentFolder?(data.folders.find(f=>f.id===currentFolder)?.name||"文件夹"):"全部网页";$("backToAllButton").hidden=!currentFolder;$("htmlGrid").innerHTML=items.length?items.map(i=>`<article class="resource-card"><div class="card-icon">&lt;/&gt;</div><h3 class="card-title">${esc(i.title)}</h3><p class="card-description">${esc(i.description||"暂无说明")}</p><p class="card-meta">${esc(data.folders.find(f=>f.id===i.folderId)?.name||"未分类")}</p><div class="card-actions"><button class="mini-button" data-open-html="${i.id}">开启</button>${actions("item",i.id)}</div></article>`).join(""):`<div class="empty-state">${isAdmin?'这里还没有 HTML 网页。点击右上角“添加 HTML”。':'这里还没有 HTML 网页。'}</div>`}
function render(){renderNav();renderAuth();$("dashboardView").hidden=!!currentSubject;$("subjectView").hidden=!currentSubject;$("pageTitle").textContent=currentSubject?`${currentSubject} 资源库`:"资源总览";currentSubject?renderSubject():renderDashboard()}
function selectSubject(id){currentSubject=id||null;currentFolder=null;$("searchInput").value="";searchTerm="";render();$("sidebar").classList.remove("open")}
function requireAdmin(){if(!user){toast("请先使用管理员 Google 账号登录");return false}if(!isAdmin){toast("这个账号没有编辑权限");return false}return true}
function fillFolders(selected=""){$("htmlFolder").innerHTML='<option value="">未分类</option>'+data.folders.filter(f=>f.subject===currentSubject).map(f=>`<option value="${f.id}" ${f.id===selected?"selected":""}>${esc(f.name)}</option>`).join("")}
function folderDialog(id=""){if(!requireAdmin())return;const folder=data.folders.find(f=>f.id===id);$("folderId").value=id;$("folderName").value=folder?.name||"";$("folderDialogTitle").textContent=folder?"修改文件夹":"新建文件夹";$("folderDialog").showModal();$("folderName").focus()}
function htmlDialog(id=""){if(!requireAdmin())return;const item=data.items.find(i=>i.id===id);$("htmlId").value=id;$("htmlTitle").value=item?.title||"";$("htmlDescription").value=item?.description||"";$("htmlCode").value=item?.code||'<!doctype html>\n<html lang="zh-CN">\n<head>\n  <meta charset="UTF-8">\n  <meta name="viewport" content="width=device-width,initial-scale=1">\n  <title>我的教学网页</title>\n</head>\n<body>\n  <h1>开始制作</h1>\n</body>\n</html>';fillFolders(item?.folderId||currentFolder||"");$("htmlDialogTitle").textContent=item?"编辑 HTML 网页":"添加 HTML 网页";$("htmlDialog").showModal()}
function openHtml(id){const item=data.items.find(i=>i.id===id);if(!item)return;const url=URL.createObjectURL(new Blob([item.code],{type:"text/html"}));window.open(url,"_blank","noopener,noreferrer");setTimeout(()=>URL.revokeObjectURL(url),60000)}
document.addEventListener("click",async event=>{const x=event.target.closest("[data-subject],[data-open-subject],[data-open-folder],[data-edit-folder],[data-delete-folder],[data-open-html],[data-edit-html],[data-delete-html],[data-close]");if(!x)return;if(x.dataset.subject!==undefined)selectSubject(x.dataset.subject);else if(x.dataset.openSubject)selectSubject(x.dataset.openSubject);else if(x.dataset.openFolder){currentFolder=x.dataset.openFolder;renderSubject()}else if(x.dataset.editFolder)folderDialog(x.dataset.editFolder);else if(x.dataset.deleteFolder&&requireAdmin()){const id=x.dataset.deleteFolder,folder=data.folders.find(f=>f.id===id);if(confirm(`删除“${folder.name}”？文件夹内网页会变为未分类。`)){const batch=writeBatch(db);batch.delete(doc(db,"folders",id));data.items.filter(i=>i.folderId===id).forEach(i=>batch.update(doc(db,"items",i.id),{folderId:""}));await batch.commit();toast("文件夹已删除")}}else if(x.dataset.openHtml)openHtml(x.dataset.openHtml);else if(x.dataset.editHtml)htmlDialog(x.dataset.editHtml);else if(x.dataset.deleteHtml&&requireAdmin()){const item=data.items.find(i=>i.id===x.dataset.deleteHtml);if(confirm(`确定删除“${item.title}”？`)){await deleteDoc(doc(db,"items",item.id));toast("HTML 已删除")}}else if(x.dataset.close)$(x.dataset.close).close()});
$("folderForm").addEventListener("submit",async event=>{event.preventDefault();if(!requireAdmin())return;const id=$("folderId").value,name=$("folderName").value.trim(),payload={subject:currentSubject,name,updatedAt:serverTimestamp()};id?await updateDoc(doc(db,"folders",id),payload):await addDoc(collection(db,"folders"),{...payload,createdAt:serverTimestamp()});$("folderDialog").close();toast(id?"文件夹已更新":"文件夹已建立")});
$("htmlForm").addEventListener("submit",async event=>{event.preventDefault();if(!requireAdmin())return;const id=$("htmlId").value,payload={subject:currentSubject,folderId:$("htmlFolder").value,title:$("htmlTitle").value.trim(),description:$("htmlDescription").value.trim(),code:$("htmlCode").value,updatedAt:serverTimestamp()};id?await updateDoc(doc(db,"items",id),payload):await addDoc(collection(db,"items"),{...payload,createdAt:serverTimestamp()});$("htmlDialog").close();toast(id?"HTML 已更新":"HTML 已储存到云端")});
$("newFolderButton").onclick=()=>currentSubject?folderDialog():toast("请先进入一个科目");$("newHtmlButton").onclick=()=>currentSubject?htmlDialog():toast("请先进入一个科目");$("backToAllButton").onclick=()=>{currentFolder=null;renderSubject()};$("searchInput").oninput=e=>{searchTerm=e.target.value.trim().toLowerCase();render()};$("menuButton").onclick=()=>$("sidebar").classList.toggle("open");
addAuthButton();onAuthStateChanged(auth,currentUser=>{user=currentUser;isAdmin=(currentUser?.email||"").toLowerCase()===ADMIN_EMAIL.toLowerCase();render();if(user&&!isAdmin)toast("已登录为访客，只能查看资源")});
onSnapshot(collection(db,"folders"),snapshot=>{data.folders=snapshot.docs.map(d=>({id:d.id,...d.data()}));render()},error=>{console.error(error);toast("无法读取云端文件夹，请检查 Firestore Rules")});
onSnapshot(collection(db,"items"),snapshot=>{data.items=snapshot.docs.map(d=>({id:d.id,...d.data()}));render()},error=>{console.error(error);toast("无法读取云端网页，请检查 Firestore Rules")});
render();
